### ISSUE TITLE
Rewrite all `./examples/.interop` to v10

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2152]
Feel free to submit PRs with migrating all of the examples here to the new version: https://github.com/trpc/trpc/tree/next/examples/.interop

 
1. copy folder to `/examples`
2. update `package.json` and remove `-interop` in the name
3. go through code and change it to `initTRPC()`-style stuff and remove old routers

All examples should run with `yarn dev` after `yarn` have ben run once in the root

Note: I want to keep all the existing interop examples -- they are there to ensure that the backward compatibility work

---
- [x] `cloudflare-workers`
- [x] `express-server`
- [ ] `express-trpc-shield`
- [x] `fastify-server` (needs update after #2114)
- [x] [`kitchen-sink`](https://github.com/trpc/examples-kitchen-sink) ~(blocked by #2113)~
- [x] `lambda-api-gateway` 🚧  #2165
- [x] `next-minimal-starter` 🚧  #2169
- [x] `next-prisma-starter` (blocked by #2113 + #2114)
- [x] `next-prisma-starter-websockets` ~(blocked by #2113)~
- [x] `next-prisma-todomvc` (blocked by #2113)
- [x] `standalone-server` (needs update after #2114)
- [x] `trpc-openapi`  (@jlalmes)
- [ ] [`zart`](https://github.com/trpc/zart) - outlined in #2118

**Comment by Nsttt** [comment]
Adding a basic zart example. I see there's none at the moment.

**Comment by KATT** [comment]
> Adding a basic zart example. I see there's none at the moment.

@Nsttt see #2118, @zomars is working on it :)

**Comment by Nsttt** [comment]
Ah, got it 😊. I'll move into other stuff then.

**Comment by Nsttt** [comment]
> > Adding a basic zart example. I see there's none at the moment.
> 
> @Nsttt see #2118, @zomars is working on it :)

Ah, got it 😊. I'll move into other stuff then.

**Comment by KATT** [comment]
> > > Adding a basic zart example. I see there's none at the moment.
> > 
> > 
> > @Nsttt see #2118, @zomars is working on it :)
> 
> Ah, got it 😊. I'll move into other stuff then.

Or [reach out to zomars](http://trpc.io/discord) to see if you can help, he's on our discord!

**Comment by AlvaroAquijeDiaz** [comment]
is `next-prisma-starter` updated to v.10 yet? And should the new version be used in production or wait for an official release?

**Comment by KATT** [comment]
> is `next-prisma-starter` updated to v.10 yet? And should the new version be used in production or wait for an official release?

@AlvaroAquijeDiaz 
You can use https://github.com/trpc/trpc/tree/next/examples/next-prisma-starter, see note at the top of https://trpc.io/docs/v10/migrate-from-v9-to-v10
