### ISSUE TITLE
Next major breaking changes

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#549]
- [x] Align to JSON-RPC2 (#6)
- [x] Move `transformers` to router (#545)
- [x] Stop exporting classes (`Router / TRPCClient` - only export the `type`s so I am able to refactor to stop using classes) - #570
- [ ] ~Rename `middleware()`?~ fix docs
- [x] delete `useLiveQuery`  - #568 
- [x] delete subs on http
- [x] make sure http reqs have req ids - #569 
- [x] remove `transformer` as part of http handler (previously deprecated) #571 
- [x] flatten client.fetchOpts - #570
- [x] withTRPC refactor - 
- change http req id to null

8.1?

- [ ] add subs on http - explicitly enabled
- [ ] make link for http based subscriptions
- [ ] ~rename splitLink left/right~
